server {
    listen 80;
    server_name kiger.sooda.moe;

    # ACME challenge for certbot renewal
    location /.well-known/acme-challenge/ {
        root /var/www/kiger;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name kiger.sooda.moe;

    ssl_certificate sites-available/cert/kiger.sooda.moe.cert.pem;
    ssl_certificate_key sites-available/cert/kiger.sooda.moe.key.pem;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://127.0.0.1:53824;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 5m;
    }
}
